env_config:
  h_tilde_path: "environment/scenario_1/h_tilde.pickle"
  devices_positions_path: "environment/scenario_1/device_positions.pickle"
  num_devices: 10
  L_max: 10
  T: 0.001
  D: 8000
  qos_threshold: 0.1
  P_sum: 0.00316
  max_steps: 10000
  algorithm: "LearnInterfaceAndPower" # Literal["Random", "LearnInterfaceAndPower", "LearnInterface", "WaterFilling", "RAQL"]

  reward_coef:
    reward_qos: 1
    reward_power: 10

seed: 1
num_envs: 1
num_episodes_per_env: 1
learning_rate: 1e-2