env_config:
  h_tilde_path: '/home/nguyen/Projects/Group ICN/Power Allocation/Source Code/environment/h_tilde.pickle'
  devices_positions_path: '/home/nguyen/Projects/Group ICN/Power Allocation/Source Code/environment/device_positions.pickle'
  L_max: 10
  T: 0.001
  D: 8000
  qos_threshold: 0.1
  P_sum: 0.06325
  max_steps: 10000
  algorithm: "LearnInterface" # Literal["Random", "LearnInterfaceAndPower", "LearnInterface", "WaterFilling"]

  reward_coef:
    reward_qos: 10
    reward_power: 10

seed: 1
num_envs: 1
num_episodes_per_env: 1
learning_rate: 1e-2